spring:
  application:
    name: users

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/test

axon:
  axonserver:
    client-id: user-service


management:
  tracing:
    enabled: false

  metrics:
    export:
      prometheus:
        enabled: false  # ????????? ??????? ?????? Prometheus
    distribution:
      percentiles-histogram:
        "[http.server.requests]": false

