spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://localhost:5432/autoTradingSystem
    username: postgres
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: users
    show-sql: false

#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: users
#
axon:
  axonserver:
    client-id: user-service

server:
  port: 8086
#
#management:
#  tracing:
#    enabled: false
#
#  metrics:
#    export:
#      prometheus:
#        enabled: false  # ????????? ??????? ?????? Prometheus
#    distribution:
#      percentiles-histogram:
#        "[http.server.requests]": false

