name: project cicd flow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Extract version from branch or tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi
          


      - name: Update POM version
        run: mvn versions:set -DnewVersion=$VERSION

      - name: Build with Maven (excluding specific modules)
        run: mvn clean install

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: '**/target/*.jar'

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: [ build, tests ]
    if: |
      startsWith(github.ref, 'refs/heads/dev-') ||
      startsWith(github.ref, 'refs/heads/release-') ||
      github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo "VERSION=${{ env.VERSION }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}


      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/autotsgroup/users-axon/app:${{ env.VERSION }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/autotsgroup/users-axon/app:${{ env.VERSION }}
  
